name: Build and deploy to Cloud Run

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: |
          export DOCKER_BUILDKIT=1
          docker pull gcr.io/cloudrun/placeholder:latest || true
          docker build --pull --cache-from gcr.io/cloudrun/placeholder:latest -t gcr.io/cloudrun/placeholder:latest .
          docker tag gcr.io/cloudrun/placeholder:latest gcr.io/cloudrun/placeholder:latest
      
      - name: Log in to Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
      
      - name: Push Docker image
        run: |
          docker push gcr.io/cloudrun/placeholder:latest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy placeholder \
            --image gcr.io/cloudrun/placeholder:latest \
            --region=asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --vpc-connector connector-cloudrun-sg

  clean:
    name: Clean up Docker images
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Remove dangling Docker images
        run: docker rmi $(docker images -f dangling=true) || true
      
      - name: Remove built Docker image
        run: docker rmi gcr.io/cloudrun/placeholder:latest