name: "running unit test, build docker image"
on:
  push:
    branches:
      - development
jobs:
  build-push-gcr:
    name: "Build and Push to GCP"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: newsynapsis
      PROJECT_ID: synapsis-417214
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet

      - name: Push Docker Image
        run: docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          